name: Checkout Demo

on: push

jobs:
  checkout-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Show files
        run: ls -la

      - name: Show current directory
        run: pwd

      - name: Read README
        run: cat README.md
