name: Trigger Demo

on:
  push:
    branches:
      - main

  workflow_dispatch:

jobs:
  trigger-job:
    runs-on: ubuntu-latest

    steps:
      - name: Print trigger info
        run: |
          echo "Workflow triggered!"
          echo "Event name: $GITHUB_EVENT_NAME"
